### ISSUE TITLE
possible to factor out a reusable npm library, not dependent on React?

### ISSUE THREAD

**Issue by vassudanagunta** [tone-row/flowchart-fun#16]
There would be a lot more users if such a library were available!

**Comment by rob-gordon** [comment]
Good timing! I just opened a PR to lay the groundwork for that. 
https://github.com/tone-row/flowchart-fun/pull/17

I'll leave this issue open until it's actually working.

**Comment by james-powis** [comment]
I would also like to add ability/documentation for shapes and connections output in a easy to utilize data object.

Something along the lines of (yaml for ease):

```
(foo) foobar
(bin) binbar
  (foo)
```
  
```yaml
shapes:
  - alias: foo
     line: 1
     text: foobar
  - alias:bin
     line: 3
     text: binbaz
connections:
  - source:
       alias: bin
       line: 3
     desitnation:
       alias: foo
       line: 1
```
